### ISSUE TITLE
build Dockerfile fail

### ISSUE THREAD

**Issue by MatteoKDev** [vfarcic/books-ms#22]
Hi,

I am following the book The DevOps 2.0 Toolkit.
Page 70, Running Pre-Deployment Tests, Compiling and Packaging the Code.

My pc has 8GB ram and 50GB free diskspace

In the virtual machine `cd` I cloned the `books-ms` repository in `/home/vagrant/books-ms`

When i run the command
```
docker build -f Dockerfile.test -t 10.100.198.200:5000/books-ms-tests .
```
I get the error in Step 25
```
npm ERR! Linux 3.13.0-105-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED
npm ERR!     at exports._errnoException (util.js:746:11)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   parent: 'jshint' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /source/client/npm-debug.log
The command '/bin/sh -c cd /source/client && npm install && bower install --allow-root --config.interactive=false -s' returned a non-zero code: 1
```

npm install run successfully from the pc terminal (osx's terminal).
What could be the problem? 

Thank you!
MatteoK

**Comment by MatteoKDev** [comment]
Using `setup_4.x` in `Dockerfile.test line 12` the build was successful.

Then, the next step:
```docker-compose -f docker-compose-dev.yml run --rm tests```
Gives the following error:
```WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).```

**Comment by vfarcic** [comment]
Can you confirm that you are not behind a firewall/proxy?

**Comment by MatteoKDev** [comment]
Thank you! I was able to complete the chapter (:

Yes, I confirm that I am not behind a firewall/proxy.

I was able to workaround using docker command instead of docker-compose, as explained in page 64:
```
sudo docker run -it --rm \
-v $PWD/client/components:/source/client/components \
-v $PWD/client/test:/source/client/test \
-v $PWD/src:/source/src \
-v $PWD/target/scala-2.10:/source/target/scala-2.10 \
-v $PWD/client/wct-complete.conf.js:/source/client/wct.conf.js \
-v $PWD/data/tests/db:/data/db \
-p 8080:8080 \
--env TEST_TYPE=all \
10.100.198.200:5000/books-ms-tests
```
then in order to execute command in page 75:
```
docker build -t 10.100.198.200/books-ms .
```
I had to give read permission to some file in `/data/tests/db/`

**Comment by vfarcic** [comment]
I'm glad it worked out. Please let me know if you encounter any other problem and I'll do my best to help you out.
