### ISSUE TITLE
vagrant up dev thorowing error

### ISSUE THREAD

**Issue by blrk** [vfarcic/books-ms#64]
Hi I am teaching DevOps for the university students. I am following your book.
I cloned https://github.com/vfarcic/books-ms.git

When I run vagrant ssh dev It throws the following error

I am able to  login using "vagrant ssh"

but unfortunately docker is not installed

``` bash
blrk@devops:~/books-ms$ vagrant destroy
    dev: Are you sure you want to destroy the 'dev' VM? [y/N] y
==> dev: Forcing shutdown of VM...
==> dev: Destroying VM and associated drives...
blrk@devops:~/books-ms$ vagrant up dev 
Bringing machine 'dev' up with 'virtualbox' provider...
==> dev: Importing base box 'ubuntu/trusty64'...
==> dev: Matching MAC address for NAT networking...
==> dev: Checking if box 'ubuntu/trusty64' is up to date...
==> dev: Setting the name of the VM: books-ms_dev_1597939457465_53975
==> dev: Clearing any previously set forwarded ports...
==> dev: Clearing any previously set network interfaces...
==> dev: Preparing network interfaces based on configuration...
    dev: Adapter 1: nat
    dev: Adapter 2: hostonly
==> dev: Forwarding ports...
    dev: 22 (guest) => 2222 (host) (adapter 1)
==> dev: Running 'pre-boot' VM customizations...
==> dev: Booting VM...
==> dev: Waiting for machine to boot. This may take a few minutes...
    dev: SSH address: 127.0.0.1:2222
    dev: SSH username: vagrant
    dev: SSH auth method: private key
    dev: Warning: Connection reset. Retrying...
    dev: Warning: Connection reset. Retrying...
    dev: Warning: Remote connection disconnect. Retrying...
    dev: Warning: Connection reset. Retrying...
    dev: Warning: Connection reset. Retrying...
    dev: Warning: Connection reset. Retrying...
    dev: 
    dev: Vagrant insecure key detected. Vagrant will automatically replace
    dev: this with a newly generated keypair for better security.
    dev: 
    dev: Inserting generated public key within guest...
    dev: Removing insecure key from the guest if it's present...
    dev: Key inserted! Disconnecting and reconnecting using new SSH key...
==> dev: Machine booted and ready!
==> dev: Checking for guest additions in VM...
    dev: The guest additions on this VM do not match the installed version of
    dev: VirtualBox! In most cases this is fine, but in rare cases it can
    dev: prevent things such as shared folders from working properly. If you see
    dev: shared folder errors, please make sure the guest additions within the
    dev: virtual machine match the version of VirtualBox you have installed on
    dev: your host and reload your VM.
    dev: 
    dev: Guest Additions Version: 4.3.40
    dev: VirtualBox Version: 5.2
==> dev: Configuring and enabling network interfaces...
==> dev: Mounting shared folders...
    dev: /vagrant => /home/blrk/books-ms
==> dev: Running provisioner: shell...
    dev: Running: /tmp/vagrant-shell20200820-10022-1obgzl7.sh
    dev: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
    dev: Installing Ansible...
    dev: Reading package lists...
    dev: Building dependency tree...
    dev: 
    dev: Reading state information...
    dev: software-properties-common is already the newest version.
    dev: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    dev:  Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications— automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.
    dev: 
    dev: http://ansible.com/
    dev:  More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
    dev: gpg: 
    dev: keyring `/tmp/tmpmupszcq2/secring.gpg' created
    dev: gpg: keyring `/tmp/tmpmupszcq2/pubring.gpg' created
    dev: gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
    dev: gpg: /tmp/tmpmupszcq2/trustdb.gpg: trustdb created
    dev: gpg: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
    dev: gpg: Total number processed: 1
    dev: gpg:               imported: 1  (RSA: 1)
    dev: OK
    dev: Get:1 http://ppa.launchpad.net trusty InRelease [15.9 kB]
    dev: Ign http://archive.ubuntu.com trusty InRelease
    dev: Get:2 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
    dev: Get:3 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
    dev: Get:4 http://ppa.launchpad.net trusty/main amd64 Packages [705 B]
    dev: Get:5 http://security.ubuntu.com trusty-security/main Sources [172 kB]
    dev: Get:6 http://ppa.launchpad.net trusty/main Translation-en [492 B]
    dev: Hit http://archive.ubuntu.com trusty-backports InRelease
    dev: Hit http://archive.ubuntu.com trusty Release.gpg
    dev: Get:7 http://archive.ubuntu.com trusty-updates/main Sources [431 kB]
    dev: Get:8 http://security.ubuntu.com trusty-security/universe Sources [103 kB]
    dev: Get:9 http://security.ubuntu.com trusty-security/main amd64 Packages [835 kB]
    dev: Get:10 https://esm.ubuntu.com trusty-infra-security InRelease
    dev: Get:11 http://archive.ubuntu.com trusty-updates/restricted Sources [6,313 B]
    dev: Get:12 http://archive.ubuntu.com trusty-updates/universe Sources [231 kB]
    dev: Get:13 https://esm.ubuntu.com trusty-infra-updates InRelease
    dev: Get:14 http://security.ubuntu.com trusty-security/universe amd64 Packages [295 kB]
    dev: Get:15 https://esm.ubuntu.com trusty-infra-security/main amd64 Packages
    dev: Get:16 http://archive.ubuntu.com trusty-updates/multiverse Sources [7,535 B]
    dev: Get:17 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1,177 kB]
    dev: Get:18 http://security.ubuntu.com trusty-security/main Translation-en [448 kB]
    dev: Get:19 http://security.ubuntu.com trusty-security/universe Translation-en [162 kB]
    dev: Get:20 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [17.2 kB]
    dev: Get:21 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [525 kB]
    dev: Get:22 https://esm.ubuntu.com trusty-infra-security/main Translation-en_US
    dev: Get:23 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [14.6 kB]
    dev: Get:24 http://archive.ubuntu.com trusty-updates/main Translation-en [582 kB]
    dev: Get:25 https://esm.ubuntu.com trusty-infra-updates/main Translation-en_US
    dev: Get:26 http://archive.ubuntu.com trusty-updates/multiverse Translation-en [7,616 B]
    dev: Get:27 http://archive.ubuntu.com trusty-updates/restricted Translation-en [4,028 B]
    dev: Get:28 http://archive.ubuntu.com trusty-updates/universe Translation-en [281 kB]
    dev: Get:29 http://archive.ubuntu.com trusty-backports/main Sources [9,709 B]
    dev: Get:30 http://archive.ubuntu.com trusty-backports/restricted Sources [28 B]
    dev: Get:31 http://archive.ubuntu.com trusty-backports/universe Sources [35.4 kB]
    dev: Get:32 http://archive.ubuntu.com trusty-backports/multiverse Sources [1,896 B]
    dev: Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty-backports/main Translation-en
    dev: Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
    dev: Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
    dev: Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
    dev: Hit http://archive.ubuntu.com trusty Release
    dev: Get:33 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
    dev: Ign https://esm.ubuntu.com trusty-infra-security/main Translation-en_US
    dev: Ign https://esm.ubuntu.com trusty-infra-security/main Translation-en
    dev: Get:34 http://archive.ubuntu.com trusty/restricted Sources [5,433 B]
    dev: Ign https://esm.ubuntu.com trusty-infra-updates/main Translation-en_US
    dev: Get:35 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
    dev: Ign https://esm.ubuntu.com trusty-infra-updates/main Translation-en
    dev: Get:36 http://archive.ubuntu.com trusty/multiverse Sources [174 kB]
    dev: Hit http://archive.ubuntu.com trusty/main amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
    dev: Hit http://archive.ubuntu.com trusty/main Translation-en
    dev: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
    dev: Hit http://archive.ubuntu.com trusty/restricted Translation-en
    dev: Hit http://archive.ubuntu.com trusty/universe Translation-en
    dev: Ign http://archive.ubuntu.com trusty/main Translation-en_US
    dev: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
    dev: Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
    dev: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
    dev: Fetched 13.5 MB in 25s (529 kB/s)
    dev: Reading package lists...
    dev: Reading package lists...
    dev: Building dependency tree...
    dev: 
    dev: Reading state information...
    dev: The following extra packages will be installed:
    dev:   python-jinja2 python-markupsafe python-paramiko python-setuptools sshpass
    dev: Suggested packages:
    dev:   python-jinja2-doc
    dev: The following NEW packages will be installed:
    dev:   ansible python-jinja2 python-markupsafe python-paramiko python-setuptools
    dev:   sshpass
    dev: 0 upgraded, 6 newly installed, 0 to remove and 1 not upgraded.
    dev: Need to get 6,328 kB of archives.
    dev: After this operation, 59.7 MB of additional disk space will be used.
    dev: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main python-markupsafe amd64 0.18-1build2 [14.3 kB]
    dev: Get:2 http://ppa.launchpad.net/ansible/ansible/ubuntu/ trusty/main ansible all 2.9.12-1ppa~trusty [5,805 kB]
    dev: Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main python-jinja2 all 2.7.2-2 [161 kB]
    dev: Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-paramiko all 1.10.1-1git1ubuntu0.2 [107 kB]
    dev: Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-setuptools all 3.3-1ubuntu2 [230 kB]
    dev: Get:6 http://archive.ubuntu.com/ubuntu/ trusty/universe sshpass amd64 1.05-1 [10.5 kB]
    dev: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    dev: Fetched 6,328 kB in 6s (939 kB/s)
    dev: Selecting previously unselected package python-markupsafe.
    dev: (Reading database ... 63238 files and directories currently installed.)
    dev: Preparing to unpack .../python-markupsafe_0.18-1build2_amd64.deb ...
    dev: Unpacking python-markupsafe (0.18-1build2) ...
    dev: Selecting previously unselected package python-jinja2.
    dev: Preparing to unpack .../python-jinja2_2.7.2-2_all.deb ...
    dev: Unpacking python-jinja2 (2.7.2-2) ...
    dev: Selecting previously unselected package python-paramiko.
    dev: Preparing to unpack .../python-paramiko_1.10.1-1git1ubuntu0.2_all.deb ...
    dev: Unpacking python-paramiko (1.10.1-1git1ubuntu0.2) ...
    dev: Selecting previously unselected package python-setuptools.
    dev: Preparing to unpack .../python-setuptools_3.3-1ubuntu2_all.deb ...
    dev: Unpacking python-setuptools (3.3-1ubuntu2) ...
    dev: Selecting previously unselected package sshpass.
    dev: Preparing to unpack .../sshpass_1.05-1_amd64.deb ...
    dev: Unpacking sshpass (1.05-1) ...
    dev: Selecting previously unselected package ansible.
    dev: Preparing to unpack .../ansible_2.9.12-1ppa~trusty_all.deb ...
    dev: Unpacking ansible (2.9.12-1ppa~trusty) ...
    dev: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    dev: Setting up python-markupsafe (0.18-1build2) ...
    dev: Setting up python-jinja2 (2.7.2-2) ...
    dev: Setting up python-paramiko (1.10.1-1git1ubuntu0.2) ...
    dev: Setting up python-setuptools (3.3-1ubuntu2) ...
    dev: Setting up sshpass (1.05-1) ...
    dev: Setting up ansible (2.9.12-1ppa~trusty) ...
==> dev: Running provisioner: shell...
    dev: Running: inline script
    dev: [WARNING]: provided hosts list is empty, only localhost is available. Note that
    dev: the implicit localhost does not match 'all'
    dev: 
    dev: PLAY [localhost] ***************************************************************
    dev: 
    dev: TASK [Gathering Facts] *********************************************************
    dev: ok: [localhost]
    dev: 
    dev: TASK [docker : Add Docker repository and update apt cache] *********************
    dev: [WARNING]: File '/etc/apt/sources.list.d/apt_dockerproject_org_repo.list'
    dev: created with default permissions '600'. The previous default was '666'. Specify
    dev: 'mode' to avoid this warning.
    dev: fatal: [localhost]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
    dev: 
    dev: PLAY RECAP *********************************************************************
    dev: localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
#<Thread:0x000055d1bca178e8@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	109: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	108: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	107: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	106: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	105: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	104: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	103: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	102: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	101: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	100: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 99: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 98: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	 97: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 96: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 95: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 94: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 93: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 92: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 91: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 90: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 89: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 88: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	 87: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 86: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 85: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 84: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 83: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 82: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 81: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 80: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 79: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 78: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 77: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 76: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 75: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 74: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 73: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 72: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	 71: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 70: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	 69: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 68: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
	 67: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 66: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/import.rb:13:in `call'
	 65: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/import.rb:74:in `import'
	 64: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 63: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	 62: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 61: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
	 60: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 59: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 58: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 57: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	 56: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 55: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 54: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 53: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_check_outdated.rb:79:in `call'
	 52: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 51: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 50: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 49: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 48: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 47: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 46: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 45: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 44: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 43: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 42: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 41: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 40: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 39: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 38: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 37: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 36: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 35: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 34: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 33: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 32: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 31: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 30: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 29: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 28: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 27: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 26: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 25: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	 24: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 23: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	 22: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	 20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:103:in `call'
	 18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:103:in `each'
	 17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:126:in `block in call'
	 16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:126:in `call'
	 15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:504:in `hook'
	 14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	  9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	  8: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `call'
	  7: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
	  6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/shell/provisioner.rb:27:in `provision'
	  5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/shell/provisioner.rb:61:in `provision_ssh'
	  4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/shell/provisioner.rb:287:in `with_script_file'
	  3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/shell/provisioner.rb:63:in `block in provision_ssh'
	  2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/shell/provisioner.rb:63:in `tap'
	  1: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/shell/provisioner.rb:89:in `block (2 levels) in provision_ssh'
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:257:in `execute': The SSH command responded with a non-zero exit status. Vagrant (Vagrant::Errors::VagrantError)
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by vfarcic** [comment]
Unfortunately, I stopped maintaining that book and the associated code. It was written a long time ago and I believe that some of the tech and the practices in it are not relevant anymore. That's why I removed the book from all the vendors I control a year or two ago. I can send you a copy of one of my other books if that helps.

**Comment by blrk** [comment]
Thank you for your quick reply. I understand the problem now. I am really struggling to teach the students. Please share the copy of  other book. I will be a great help.

**Comment by vfarcic** [comment]
Can you please send me an email to viktor@farcic.com? I'll respond with a link to download a free copy of https://www.devopstoolkitseries.com/posts/devops-23/ (you can choose a different one from that site).

**Comment by blrk** [comment]
Hi Victor I have sent an email. Thank you.

**Comment by blrk** [comment]
Thank you
